# Generated by Django 5.2.8 on 2025-11-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor_o_editorial',
            new_name='autor',
        ),
    ]
