# Generated by Django 5.2.7 on 2025-11-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_libro_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('autor', 'Autor'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
