# Generated by Django 5.2.7 on 2025-11-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_libro_alquiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='prestado', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='eleccion_libro',
            field=models.CharField(choices=[('prestado', 'Prestado'), ('ventade', 'Venta'), ('alquiler', 'Alquiler')], default='prestado', max_length=10),
        ),
        migrations.AddField(
            model_name='libro',
            name='isbn',
            field=models.CharField(default='123', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=6),
            preserve_default=False,
        ),
    ]
