# Generated by Django 5.2.8 on 2025-11-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_autor_o_editorial_libro_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor',
            new_name='autor_o_editorial',
        ),
    ]
