# Generated by Django 5.2.7 on 2025-11-21 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_intercambio_vendido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libros_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
