# Generated by Django 5.2.8 on 2025-11-26 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_libro_creador_intercambio_vendido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor_o_editorial',
            new_name='autor',
        ),
    ]
