# Generated by Django 5.2.7 on 2025-12-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_libro_autor_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='usuario',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='carrito',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
