# Generated by Django 5.2.7 on 2025-12-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_compra_delete_carritoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='autor_o_editorial',
            field=models.CharField(default=10, max_length=255),
            preserve_default=False,
        ),
    ]
